### PR TITLE
prepare_app called on every request

### PR DESCRIPTION
**Pull request by domm**
When a Middleware has a dependency (resolved via Bread::Board), this Middlewares prepare_app method will be called on every request. This feels like a bug to me.

This pull request adds a test that illustrates the problem:
t/middleware_prepare_app.t

But there is a comment in the "guilty" code:
OX::Application::Role::Sugar -> around 'to_app'  lines 88ff

The comment seems to indicate that Middlewares with dependencies need to be re-evaled on each request. I don't know enough OX internals to understand the issue here, but it makes complex middlewares rather unusable (and thus OX...)
Even Plack::Middleware::Session will not cache its state/store...

When I tried to remove the around to_app code, my test works, but 
t/middleware_dependencies.t 
failed

Any ideas what to do?

### CODE REVIEW

**Comment by domm** [comment]
I've now added some code that fixes the problem, while still keeping all tests working:

The solution was to introspect the dependecies when adding a new Middleware. If all dependecies of a middleware are of lifecycle = Singleton, the Middelware will not be reresolved on each request.

To implement this, I added a new attib 'needs_reresolve' to OX::Meta::Middleware and OX::Meta::Role::HasMiddleware. In OX::Application::Role::Sugar around to_app I check if this attrib is set, and act accordingly.

I'm still not sure if this is the right way - any feedback is appreciated!

Greetings,
domm

**Comment by stevan** [comment]
@domm I will try and take a look sometime today (it is a holiday here in the US) or if I can't manage that I will look into it tomorrow. Your approach sounds sane and reasonable though.

**Comment by domm** [comment]
ok, no need to hurry (or waste a holiday) - we're not running anything live yet...

(but of course getting to a solution in the next few days would be great!)

Greetings,
domm

**Comment by doy** [comment]
I don't like this. First of all, the implementation is wrong in a couple ways - you can have inline dependencies that aren't just literals (so only skipping dependencies which are Bread::Board::Literal instances is wrong), and attributes and services are different things (you should be using `fetch` rather than `get_attribute`). On a more conceptual level though, I really don't like the idea of hardcoding a match against "Singleton", since Bread::Board lifecycles are themselves an implementation of some functionality, not just tags for something external to look at. If I copy the implementation of Bread::Board::LifeCycle::Singleton into a new role with a different name, this code here should not just stop working.

I don't have time currently to look into a proper fix (maybe in a week or so), but I don't think that this current patch is the right way forward here.

**Comment by domm** [comment]
doy, that's quite what I expected :-)

I assumed that there are other things than Bread::Board::Literal, and hardcoding 'Singleton' seemed very wrong.

But as I lack deeper knowledge of OX internals, I just hacked a bit on the code I found via ack and on the test errors that showed up after hacking. As I already told stevan, we're in no hurry here, but we would like to know if we can expect OX to support middleware that needs to run some setup code once per process AND that depends on stuff defined in the application class.

Thanks for your feedback,
Greetings,
domm

**Comment by stevan** [comment]
I disagree on your point about Singleton. If I copy the contents of the Singleton role and change the name, then I get what I deserve, especially if the behavior is documented.

As for the code, I haven't had the time to review it yet myself. But this is on my list of stuff TODO tomorrow so I will see what I can find.

**Comment by klaus** [comment]
Understanding it is very difficult to find 'THE' solution, I was wondering if other lifecycles like e.g. 'PerPid' would be important to think about now. We would need this special lifecyclce for 0mq, where you cannot fork a 0mq context. We have found a workaround (a bit like for DBIC, storing $$ in a hash like { connect_$$ => $ctx || new_ctx }), but I have the feeling that 'prepare_app"s' intent was exactly this. 

So PerPid, Singleton match quite well with the psgi's prepare_app??

When looking at the issue i had the feeling that PerRequest is an OX addon already, why not have another addon to OX? The introspection approach can never be 100% sure of what to do.

thank you for your time!

**Comment by doy** [comment]
I have a fix for this that resolves the problems that I mentioned, but I'm still working out the API bits. Basically, I think the correct solution here is to allow you to specify lifecycles for the middleware themselves, rather than try to infer them from their dependencies. This way, you can just specify your middleware as being a Singleton directly, and everything should just work. I'll push up a sketch of the idea in a bit.

**Comment by doy** [comment]
@klaus This sounds like a separate idea. Can you submit it as a separate issue?

**Comment by domm** [comment]
Oh, I didn't see your commit 25d7b86 ...

I'll give that a try...

thanks!

**Comment by doy** [comment]
Closing this because I assume that #13 is the continuation of this? Let me know if I'm mistaken.

**Pull request closed without merging**
